/*
 * File: app/store/TicketStore.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.store.TicketStore', {
    extend: 'Ext.data.Store',
    alias: 'store.ticketStore',

    requires: [
        'TicketTracker.model.Ticket'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TicketStore',
            model: 'TicketTracker.model.Ticket',
            data: [
                {
                    title: 'Maxx Royal',
                    status: 'Open',
                    description: 'Error on Accounting module',
                    importance: 3
                },
                {
                    title: 'Akra Barut',
                    status: 'Complete',
                    description: 'Error on GEM module',
                    importance: 5
                },
                {
                    title: 'Limak Hotels',
                    status: 'In Progress',
                    description: 'Error on Reservation module',
                    importance: 2
                }
            ]
        }, cfg)]);
    }
});