/*
 * File: app/view/TicketPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TicketTracker.view.TicketPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ticketPanel',

    requires: [
        'TicketTracker.view.TicketDataView',
        'Ext.view.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 500,
    width: 700,
    title: 'Ticket Tracker',

    items: [
        {
            xtype: 'ticketDataView'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    width: 200,
                    fieldLabel: 'Importance',
                    name: 'status',
                    queryMode: 'local',
                    store: [
                        '1',
                        '2',
                        '3',
                        '4',
                        '5'
                    ]
                },
                {
                    xtype: 'button',
                    action: 'sortByImportance',
                    text: 'Sort By Importance'
                },
                {
                    xtype: 'button',
                    action: 'clearFilter',
                    text: 'Clear Filter'
                },
                {
                    xtype: 'button',
                    action: 'addTicket',
                    text: 'Add Ticket'
                }
            ]
        }
    ]

});